### ISSUE TITLE
All Level Approval Embeds have the "Reupload" message attached

### ISSUE THREAD

**Issue by social-assassin** [TeamShellSMM/ShellBot3000#68]
**Describe the bug**
All level approval embeds have the "This level was already approved before, and now your reupload is as well." Message attached

**To Reproduce**
Check #shellbot-level-updates

**Expected behavior**
Should be like how it was before, I believe this is a regression related to adding messaging surrounding reuploads/fix requests.

**Comment by a-unique-id** [comment]
So the problem seemed to have resolved itself, and we're not sure why it happened.

It only happened in TeamShell, but it could also be just during a period of time where the other teams didn't approve a level but looking at the updates, it did seem that it was localized to TeamShell
<img width="370" alt="image" src="https://user-images.githubusercontent.com/45527149/82611450-221e7100-9bf3-11ea-9e7d-f7b9fb0436a6.png">

So a possibility could be in some team settings active in TeamShell not active in other teams. But since it currently has resolved itself, and we can recreate the problem, we'll close this issue until maybe it crops up again or we find the problem

**Comment by a-unique-id** [comment]
So it started again, buzzyS. 

- Currently, we've restarted the bot and see if that "fixes" it, as the issue went away after some commits and deploy.
- Same thing, other teams are not affected, just TeamShell.
- Problem seems to start after a fix status update? Is there a possibility that a constant is getting overwritten somewhere?
- The relevant code (and the only instance where this message should be used is here)
 https://github.com/TeamShellSMM/ShellBot3000/blob/01473aa3d7b65fdab3e463f7d138b523f07b3126/src/TS.js#L1675

 - This is assigned based on `level.status` so perhaps there's something going on with that
